services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: aryaanhabib/quantumquest-backend:latest
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    image: aryaanhabib/quantumquest-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
